language : java
jdk:
  - oraclejdk11

sudo: false

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION= 1.25.2

before_script:
  - docker-compose -f docker/dev/docker-compose.yml up -d

script:
  -  mvn install -Ptest-business -Ptest-consumer

after_script:
  # Stops running containers without removing themm
  - docker-compose -f docker/dev/docker-compose.yml stop
  # Removes stopped service containers
  - docker-compose -f docker/dev/docker-compose.yml rm -f
  # Stops containers and removes containers, networks, volumes, and images created by up
  - docker-compose -f docker/dev/docker-compose.yml down

after_success:
  - mvn --file pom.xml cobertura:cobertura coveralls:report -P test-consumer,test-business
